name: "Merge on lgtm label"
on:
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 * * * *"

jobs:
  execute:
    runs-on: ubuntu-20.04
    steps:
      - uses: jpmcb/prow-github-actions@v1.1.3
        with:
          jobs: 'lgtm'
          github-token: "${{ secrets.COREDGE_GIT_CLONE_TOKEN }}"
          merge-method: 'squash'
