name: Release k8s BYOH Bundles

on:
  push:
    # Build and publish artifacts when new tag is created for release
    tags:
      - "v*.*.*"

jobs:
  build-and-publish-k8s-bundles:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Login to Docker Hub
      env:
        DOCKER_USER: ${{secrets.DOCKERHUB_USER}}
        DOCKER_PWD: ${{secrets.DOCKERHUB_USER}}
      run: docker login -u $DOCKER_USER -p $DOCKER_PWD
    
    - name: pre-cleanup the docker
      run: sudo docker system prune -a -f && sudo docker buildx prune

    - name: Build BYOH Ingredients Docker image
      run: |
        cd installer/bundle_builder/ingredients/deb/
        docker build -t byoh-ingredients-deb .

    - name: Create BYOH Ingredients directory and download files
      run: |
        mkdir -p byoh-ingredients-download
        docker run --rm -v ${{ github.workspace }}/byoh-ingredients-download:/ingredients byoh-ingredients-deb

    - name: Build BYOH Bundle Docker image
      run: |
        cd installer/bundle_builder/
        docker build -t byoh-build-push-bundle .

    - name: Build and Publish BYOH Bundle
      env:
        BUILD_ONLY: 0
        REPO: ${{ github.repository_owner }}
        BUNDLE_NAME: byoh-bundle-ubuntu_20.04.1_x86-64_k8s
        TAG: v1.31.0
      run: |
        docker run --rm -v ~/.docker/config.json:/root/.docker/config.json -v ${{ github.workspace }}/byoh-ingredients-download:/ingredients --env BUILD_ONLY=${{ env.BUILD_ONLY }} byoh-build-push-bundle $REPO/$BUNDLE_NAME:$TAG

    - name: Cleanup Docker
      run: sudo docker logout && sudo docker system prune -a -f && sudo docker buildx prune

